usr/lib/awn/applets/wobblyzini/*.so
usr/lib/awn/applets/cairo_main_menu_classic/*.so
usr/lib/awn/applets/trasher/*.so
usr/lib/awn/applets/filebrowser/*.so
usr/lib/awn/applets/main-menu/*.so
usr/lib/awn/applets/switcher/*.so
usr/share/awn/applets/wobblyzini.desktop
usr/share/awn/applets/cairo_main_menu_classic.desktop
usr/share/awn/applets/trasher.desktop
usr/share/awn/applets/filebrowser.desktop
usr/share/awn/applets/main-menu.desktop
usr/share/awn/applets/switcher.desktop
usr/lib/awn/applets/wobblyzini/icons/wobblyzini.png usr/share/awn/applets/icons/
usr/share/avant-window-navigator/applets/icons/filebrowser.svg usr/share/awn/applets/icons/
#usr/lib/awn/applets/notification-area/*.so
#usr/share/awn/applets/notification-area.desktop
#usr/share/avant-window-navigator/applets/icons/notification.svg usr/share/awn/applets/icons/
